name: Build Factory Image

on:
  workflow_dispatch:
  push:
    branches:
      - docker
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.18
          check-latest: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # - name: Login to Amazon ECR Public
      #   id: login-ecr-public
      #   uses: aws-actions/amazon-ecr-login@v2
      #   with:
      #     registry-type: public
      #     aws-region: us-east-1

      - name: Set up Docker
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: |
            "PROJECT_NAME=factory"
          tags: |
            sugarcaneai/factory:latest
          push: true

      # - name: Build, tag, and push docker image to Amazon ECR Public
      #   env:
      #     REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      #     REGISTRY_ALIAS: my-ecr-public-registry-alias
      #     REPOSITORY: my-ecr-public-repo
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
      #     docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
